require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  EnabledByDefault: true

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false
