require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  EnabledByDefault: true

Metrics/BlockLength:
  Exclude:
    - spacewar.gemspec

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false
