language: ruby
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 2.0
addons:
  code_climate:
    repo_token:
      secure: bEzlEFKKncrUr9wI2rc+nPnPOZVA0xvVo1TGSZW+qDAnbd0TGZ1V+o46CePXmD6YleotLFxW9OrLpRFk1V7dv10tWbfxMpsl86jlQg+Kqai18zQGp4ZWw8RlTvxYbMv2OgU80L5eGnBLCnJ2gQFGDTytsdAWjscR6QdYeFRZr/AIy0RiYtYopFn5rWpBJlhY/4nsPUxuahvDJNKNVBkZKJUPD3a+q90ssmiMpeq2HnPZGm9k9vQwIY5UUgame1dCmNB5bqxspliNHc2o4pnloeP74HXZQvzBjCL8mkRaMM4oDajPMFGD7glsB/ZUAiUnrsMYDX3bhG7oMUW3ikrcqmWj6hARiHtfdw+0lSeZfrPg0vK7SfPiVsUrjNDU9IMRTx9rI99x0wgK4naOvxwcPZYl08YLNqlipw4fiuqkdrmjToZL337vmdqyMRX9iIYwfW85SU0Al+aPzlJ+Ag2ETPRwGGNW74FjQEy0QLdcRlox1SY8NtCZHrWewMIBqCAI04GRtgFfILv5okzcC2+HbksZEjC93Z5ZUuHjaul3IYYLhrwEZ2/UmhSh/YRBKh85iQ/L2iJGaa44PxJSgP2uSXRCEHdSMfqvGmlnjmUMQoaok26kJO3AI/QOKSJR9/QHkYpeBpTx9F1se8YOfn/GyQ8YFw3THpg0upUJ1v94Nrg=
before_install:
  - gem install bundler --conservative
after_success:
  - bundle exec codeclimate-test-reporter
